# Generated by Django 2.2.2 on 2019-06-18 15:11

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sloc', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('cfee', models.IntegerField()),
                ('student', models.ForeignKey(null=-1, on_delete=django.db.models.fields.related.ForeignKey, to='mtoapp.Student')),
            ],
        ),
    ]
